# Generated by Django 3.2.18 on 2023-05-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20230513_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='limits',
            field=models.IntegerField(choices=[(0, '学生'), (1, '老师')], default=1, null=True, verbose_name='limits'),
        ),
    ]
