# Generated by Django 3.2.18 on 2023-05-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20230514_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='classscore',
            name='sid',
            field=models.IntegerField(default=0, verbose_name='学号'),
            preserve_default=False,
        ),
    ]
